
TOP_SRCDIR = ..
CPPFLAGS = -I../include -MMD -MP
CFLAGS = -Wall -Werror -pedantic -pthread

DEMO_LIB_DIR = ../demo-lib

CLEANEXTS = o a d

LIB_OBJS = \
	demo-utils.o

LIBRARY = libdemo.a

# Default target
all: $(LIBRARY)

$(LIBRARY): $(LIB_OBJS)
	ar ru $@ $^
	ranlib $@

#install:
#	cp $(LIBRARY) $(LIB_DIR)

clean:
	for file in $(CLEANEXTS); do rm -f *.$$file; done

.PHONY: all install clean

-include $(LIB_OBJS:.o=.d)
